# theme: 'System', 'Dark' or 'Light'
# call_countdown = 0 disable or int() in sec
[general]
version = 1.0
debug = false

[appearance]
window_title = Client viewer
theme = System
color_theme = blue
window_width = 800
window_height = 600
fullscreen = true
zoomed = true

[setup]
call_countdown = 0