[general]
version = 1.7.2
debug = false

[client]
id = A-113-local
host = 192.168.1.118
port = 8765

[audio]
sample_rate = 16000
channels = 1
# 512 fijo para docker
frame_size = 512
mange_dev_by_os = true
input_hw = hw:0,0
output_hw = hw:0,0

[video]
video_width = 640
video_height = 480
frames_second = 10
camera_device = 0

