services:
  control-client:
    build:
      context: .
      dockerfile: control_client/Dockerfile
    container_name: videocop-server
    restart: unless-stopped
    networks:
      - videocop-internal
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /home/videocop-config:/app/core
    devices:
      - /dev/gpiochip4:/dev/gpiochip4
    privileged: true

  ui-client:
    build:
      context: .
      dockerfile: ui_client/Dockerfile
    container_name: videocop-ui-client
    restart: unless-stopped
    networks:
      - videocop-internal
    environment:
      - DISPLAY=:0
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/run/user/1000
      - XAUTHORITY=/app/.Xauthority
      - PYTHONUNBUFFERED=1
    devices:
      - /dev/video0:/dev/video0
      - /dev/v4l:/dev/v4l
      - /dev/snd:/dev/snd
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /run/user/1000/wayland-0:/run/user/1000/wayland-0:rw
      - /home/admin/.Xauthority:/app/.Xauthority:ro
      - /home/videocop-config:/app/core
    depends_on:
      - control-client

networks:
  videocop-internal:
    driver: bridge